// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package assembly

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	server2 "github.com/go-hasaki/hasaki-layout-advanced/internal/app/server"
	server3 "github.com/go-hasaki/hasaki-layout-advanced/internal/server"
	"github.com/go-hasaki/hasaki-layout-advanced/internal/service"
)

// Injectors from server.go:

func NewHttpServer() (*server.Hertz, func(), error) {
	indexService := service.NewIndexService()
	indexHandler := server2.NewIndexHandler(indexService)
	hertz := server3.NewHttpServer(indexHandler)
	return hertz, func() {
	}, nil
}
